language: objective-c
osx_image: xcode9.2
#xcode_project: testTravisIntegration.xcodeproj
#xcode_scheme: testTravisIntegration
#xcode_sdk: iphonesimulator11.2

script:
    - xcodebuild clean build -sdk iphonesimulator11.2 -project testTravisIntegration.xcodeproj -scheme testTravisIntegration CODE_SIGNING_REQUIRED=NO
